- name: Update apt cache
  apt: update_cache=yes

- name: Install developer packages
  apt: 
    name:
      - build-essential
      - python3-venv
      - python3-dev
      - python-virtualenv
      - libglib2.0-dev
      - ninja-build
      - clang
      - clang-tidy
      - autoconf
      - libtool
      - libftdi-dev
      - libftdi1-dev
      - gdb
      - cmake
      - libcairo2-dev
      - libgirepository1.0-dev
      - gfortran
<<<<<<< HEAD
      - xdotool
=======
<<<<<<< HEAD
      - libeigen3-dev
=======
      - xdotool
>>>>>>> spg-auton-integration-copy
>>>>>>> 52262418 (Merged with new branch:)
    state: present
